name: errno
description: "Errno"
version: 1.0.0
homepage: https://github.com/rtmigo/xrandom

environment:
  #sdk: ">=2.12.0 <3.0.0"
  sdk: ">=1.1.1 <3.0.0"

dependencies:
  # none

dev_dependencies:
  test: ^1.5.1