name: errno
description: "Errno"
version: 0.0.0-dev
homepage: https://github.com/rtmigo/xrandom

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.5.1