name: errno
description: "Defines system error code constants for the OSs that the Dart platform is running on"
version: 1.0.1
repository: https://github.com/rtmigo/errno

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # none

dev_dependencies:
  test: ^1.5.1